name = 'bryson-tyler'
main = ".open-next/worker.js"
compatibility_date = "2026-06-26"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[assets]
directory = ".open-next/assets"